// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqealcvjzntgbbdfbxne.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxZWFsY3Zqem50Z2JiZGZieG5lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MzI2MTYsImV4cCI6MjA2NTUwODYxNn0.lkWCDmiCMfFyW9uSlQaEOC_d2T5tiulAIZjRTyKqwbY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);